In [4]:
import numpy as np
from agents import *

class VacuumAgent(Agent):

    def __init__(self, program = None):
        super().__init__(program)
        self.location = [1,1]
        self.direction = 'R' # 'R', 'L', 'U', 'D'

def program(percept):
    if percept == 2:
        return ('Suck','None')
    else:
        bump = 'Bump' if agent.bump else 'None'
        return ('Move', bump)

class Environment:
    
    def __init__(self):
        self.agents = []
        
        with open('floorplan.txt') as f:
            floor_plan = np.array([list(map(int, line.strip())) for line in f])
        self.floor_plan = floor_plan
        
    def percept(self, agent):
        return self.floor_plan[agent.location[0]][agent.location[1]]

    def execute_action(self, agent, action):
        if action[0] == 'Suck':
            self.floor_plan[agent.location[0]][agent.location[1]] = 1
            agent.performance += 100
        if action[0] == 'Move':
            agent.performance -= 1
            if action[1] == 'Bump':
                agent.direction = random.choice(['R', 'L', 'U', 'D'])
                agent.bump = False
            else:
                agent.bump = self.move_agent(agent)

    def move_agent(self, agent):
        if agent.direction == 'R':
            loc = agent.location
            if self.floor_plan[loc[0]][loc[1] + 1] == 0:
                agent.bump = True
            else:
                agent.location[1] += 1
        elif agent.direction == 'L':
            loc = agent.location
            if self.floor_plan[loc[0]][loc[1] - 1] == 0:
                agent.bump = True
            else:
                agent.location[1] -= 1
        elif agent.direction == 'U':
            loc = agent.location
            if self.floor_plan[loc[0] - 1][loc[1]] == 0:
                agent.bump = True
            else:
                agent.location[0] -= 1
        elif agent.direction == 'D':
            loc = agent.location
            if self.floor_plan[loc[0] + 1][loc[1]] == 0:
                agent.bump = True
            else:
                agent.location[0] += 1
        return agent.bump

    def step(self):
        action = agent.program(self.percept(agent))
        self.execute_action(self.agents[0], action)
        print(action, self.agents[0].location, self.agents[0].direction)

    def run(self,steps=100):
        for step in range(steps):
            self.step()
    
    def display_floor(self):
        print(self.floor_plan)

    def add_agent(self, agent):
        self.agents.append(agent)


env = Environment()
agent = VacuumAgent(program)
env.add_agent(agent)

env.display_floor()
env.run()
env.display_floor()
print(agent.performance)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 2 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 1 0 1 0 1 0 2 2 2 2 2 2 0]
 [0 0 1 0 1 1 2 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
('Move', 'None') [1, 2] R
('Move', 'None') [1, 3] R
('Suck', 'None') [1, 3] R
('Move', 'None') [1, 4] R
('Move', 'None') [1, 5] R
('Move', 'None') [1, 6] R
('Move', 'None') [1, 7] R
('Move', 'None') [1, 8] R
('Move', 'None') [1, 9] R
('Move', 'None') [1, 10] R
('Move', 'None') [1, 11] R
('Move', 'None') [1, 12] R
('Move', 'None') [1, 13] R
('Move', 'None') [1, 13] R
('Move', 'Bump') [1, 13] D
('Move', 'None') [2, 13] D
('Suck', 'None') [2, 13] D
('Move', 'None') [2, 13] D
('Move', 'Bump') [2, 13] U
('Move', 'None') [1, 13] U
('Move', 'None') [1, 13] U
('Move', 'Bump') [1, 13] U
('Move', 'None') [1, 13] U
('Move', 'Bump') [1, 13] R
('Move', 'None') [1, 13] R
('Move', 'Bump') [1, 13] D
('Move', 'None') [2, 13] D
('Move', 'None') [2, 13] D
('Move', 'Bump') [2, 13] L
('Move', 'None') [2, 12] L
('Suck', 'None') [2, 12] L
('Move

In [60]:
arr[1][1]

1